mutation BulkVerify($input: FileVerificationInput!) {
  bulkVerify(input: $input) {
    verifiedFileId
    originalFileId
    user
    updatedAt
    totalRows
    status
    startedAt
    createdAt
    completedAt
    _id
  }
}