mutation FileProcessingStatus($fileId: String!) {
  fileProcessingStatus(fileId: $fileId) {
    _id
    duplicateCount
    invalidCount
    percentage
    processedRows
    totalRows
    validCount
  }
}