mutation GetFileVerification($fileVerficationId: String!) {
  getFileVerification(fileVerficationId: $fileVerficationId) {
    _id
    completedAt
    createdAt
    originalFile{
      filename
    }
    startedAt
    status
    totalRows
    updatedAt
    user
    verifiedFileId
    metadata {
      valid
      invalid
      duplicate
    }
  }
}