mutation GetFileVerifications($input: PaginatedFileVerificationDto!) {
  getFileVerifications(input: $input) {
    edges {
      cursor
      node {
        _id
        completedAt
        createdAt
        originalFile{
          _id
          filename
          size 
        }
        startedAt
        status
        totalRows
        updatedAt
        user
        verifiedFileId
        metadata {
          valid
          invalid
          duplicate
        }
      }
    }
    pageInfo {
      endCursor 
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}