query GetFileVerifications($input: PaginatedFileVerificationDto!) {
  getFileVerifications(input: $input) {
    edges {
      cursor
      node {
        ...FileVerificationFields
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}