fragment FileVerificationFields on FileVerificationModel {
  _id
  status
  totalRows
  startedAt
  completedAt
  createdAt
  updatedAt
  originalFile {
    _id
    filename
    size
  }
  verifiedFileId

  metadata {
    valid
    invalid
    duplicate
  }
}
