query GetInvoices($input: PaginatedInvoiceDto!) {
  getInvoices(input: $input) {
    edges {
      cursor
      node {
        ...InvoiceFields
      }
    }
    pageInfo {
      startCursor
      hasPreviousPage
      hasNextPage
      endCursor
    }
  }
}