query GetSubscriptions($input: PaginatedSubscriptionDto!) {
  getSubscriptions(input: $input) {
    edges {
      cursor
      node {
        ...SubscriptionFields
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}